on:
  push:
    branches:
      - main

name: 패키지를 출판해요 - main

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  publish-package:
    name: 패키지를 출판해요
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: 패키지를 설치하고 릴리즈를 만들어요
        run: |
          yarn install
        shell: bash

      - name: build
        run: |
          yarn build
        shell: bash

      - name: 릴리즈 Pull Request를 만들거나 패키지를 배포해요
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          version: yarn version
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
